eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8760/eureka/
server:
  port: 9999

spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xiaolei002/springcloud
          searchPaths: src/main/resources
          username: xiaolei002
          password: guoshanglei123
  application:
    name: config-server