server:
  port: 9999

spring:
  cloud:
    config:
      #分支
      label: master
      server:
        #git地址
        git:
          uri: https://github.com/xiaolei002/springcloud
          #相对路径
          searchPaths: src/main/config
          username: xiaolei002
          password: guoshanglei123
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8760/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10